server.port=8080
auth.jwt.secret=smart-campus-group58-local-demo-secret-2026
auth.jwt.expiration-seconds=86400

auth.seed.user.name=Group 58 Student
auth.seed.user.email=student@example.com
auth.seed.user.password=ChangeMe123!

auth.seed.admin.name=Group 58 Admin
auth.seed.admin.email=admin@example.com
auth.seed.admin.password=ChangeMe123!
